# SonarQube project configuration
# Docs: https://docs.sonarsource.com/sonarqube-community-build/analyzing-source-code/scanners/sonarscanner/

sonar.projectKey=devsecops-platform
sonar.projectName=DevSecOps Platform Demo
sonar.sources=app
sonar.language=py
sonar.sourceEncoding=UTF-8
